services:
    dmzx.notifyadmin.listener:
        class: dmzx\notifyadmin\event\listener
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '@template'
            - '@request'
            - '@service_container'
            - '%core.php_ext%'
            - '%core.root_path%'
        tags:
            - { name: event.listener }
 